name: 'Publish @melon-design/react'

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release type'
        options:
          - patch
          - minor
          - major
          - beta
          - alpha
          - next

jobs:
  publish-new-version:
    name: 'Publish a new version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build:react
      - name: Get new version
        run: echo "RELEASE_VERSION="$(node scripts/new-version.js)"" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
      - name: Change version
        run: |
          if [[ -z $RELEASE_VERSION ]]; then
            echo "new version is empty"
            exit 1
          fi

          git config --global user.name 'John Zhang'
          git config --global user.email 'iamjz210@gmail.com'

          echo "New version: $RELEASE_VERSION"
          pnpm version -w @melon-design/react $RELEASE_VERSION --allow-same-version --no-commit-hooks --no-workspaces-update
      - name: Publish
        run: |
          npm config set registry=https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm whoami

          DIST_TAG=latest
          if [[ ${{ github.event.inputs.release_type }} == 'beta' ]]; then
            DIST_TAG=beta
          elif [[ ${{ github.event.inputs.release_type }} == 'alpha' ]]; then
            DIST_TAG=alpha
          elif [[ ${{ github.event.inputs.release_type }} == 'next' ]]; then
            DIST_TAG=next
          fi

          echo "Dist tag: $DIST_TAG"

          pnpm publish:react -r --tag $DIST_TAG --no-git-checks
      - name: Git push
        run: |
          git push -o ci.skip --follow-tags --no-verify --atomic
