name: 'publish'

on:
  workflow_dispatch:
    inputs:
      dist_tag:
        description: 'dist-tag: Default to latest'
        default: latest
      version:
        type: choice
        description: 'version type'
        options:
          - Patch
          - Minor
          - Major

jobs:
  publish-new-version:
    name: 'publish a new version'
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          echo ${{ github.event.inputs.dist_tag }}
          echo ${{ github.event.inputs.version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Get version list
        run: |
          PKG_NAME=@melon-design/react
          echo "VERSION_LIST="$(npm view $PKG_NAME versions --json)"" >> $GITHUB_ENV
      # - name: Get new version
      #   run: echo "RELEASE_VERSION="$(node scripts/version.js)"" >> $GITHUB_ENV
      #   env:
      #     DIST_TAG: ${{ github.event.inputs.dist_tag }}
      #     VERSION_TYPE: ${{ github.event.inputs.version }}
      # - name: publish
      #   run: |
      #     git config --global user.name 'John Zhang'
      #     git config --global user.email 'iamjz210@gmail.com'
      #     npm config set registry=https://registry.npmjs.org/
      #     npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      #     npm whoami
      #     DIST_TAG=${{ github.event.inputs.release_type }}
      #     echo "$RELEASE_VERSION"
      #     echo "$DIST_TAG"
      #     pnpm version $RELEASE_VERSION
      #     pnpm build -r --tag $DIST_TAG --no-git-checks
